site_name: Maciej Poborca CV
theme:
  name: material
plugins:
    - page-to-pdf
    - search
nav:
    - CV: 'index.md'
    - test: 'test.md'
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format